### ISSUE TITLE
✅ UI : 탭페이저, 저축, 카드, 투자, 대출 페이지 구현

### ISSUE THREAD

**Issue by seoyeonsw** [GDG-24-25-KAKAOBANK-Android/GDG-Team1#19]
# 📝 Description
이번 주차 백서연 담당 끝내기!

## 📌 Todo
- [ ] 탭 페이저 구현하기!
- [ ] 상품 - 저축 페이지 구현
- [ ] 상품 - 카드 페이지 구현
- [ ] 상품 - 투자 페이지 구현
- [ ] 상품 - 대출 페이지 구현
